# Policy for verifying the blob-cli source archive
#
# This policy verifies:
# 1. Sigstore signature from the publish-src workflow on master
# 2. SLSA provenance from the meigma/blob-cli repository on master

signature:
  keyless:
    issuer: https://token.actions.githubusercontent.com
    identity: https://github.com/meigma/blob-cli/.github/workflows/publish-src.yml@refs/heads/master

provenance:
  slsa:
    repository: meigma/blob-cli
    branch: master
