# Policy for verifying the blob-cli source archive
#
# This policy is intended for use with `blob verify` once tag-based attestation
# discovery is supported. Currently, the SLSA generator uses tag-based storage
# (sha256-<digest>.att) which the blob CLI doesn't yet discover.
#
# The workflow validates attestations manually using oras until this is implemented.
#
# TODO: Enable policy verification once blob library supports tag-based attestation discovery

provenance:
  slsa:
    repository: meigma/blob-cli
    branch: master
